# Generated by Django 6.0.7 on 2026-07-14 04:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_instances', '0001_initial'),
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('SKIPPED', 'Skipped'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_stops', to='job_instances.jobinstance')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instance_stops', to='stops.stop')),
            ],
            options={
                'db_table': 'instance_stops',
                'ordering': ['sequence_number'],
            },
        ),
    ]
