# Generated by Django 6.0.7 on 2026-07-14 00:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="bulk_uploads/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("failed_rows", models.IntegerField(default=0)),
                ("error_report", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_uploads",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "bulk_uploads",
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("registration_number", models.CharField(max_length=100)),
                ("vin", models.CharField(blank=True, default="", max_length=100)),
                (
                    "chassis_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("manufacturer", models.CharField(max_length=255)),
                ("model", models.CharField(max_length=255)),
                ("variant", models.CharField(blank=True, default="", max_length=255)),
                ("manufacture_year", models.IntegerField()),
                ("purchase_date", models.DateField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("bus", "Bus"),
                            ("truck", "Truck"),
                            ("car", "Car"),
                            ("van", "Van"),
                            ("trailer", "Trailer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("diesel", "Diesel"),
                            ("petrol", "Petrol"),
                            ("ev", "Ev"),
                            ("cng", "Cng"),
                            ("lpg", "Lpg"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("engine_cc", models.IntegerField(blank=True, null=True)),
                (
                    "fuel_tank_capacity",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "battery_capacity_kwh",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("mileage_kmpl", models.DecimalField(decimal_places=2, max_digits=6)),
                ("payload_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                ("seating_capacity", models.IntegerField()),
                ("gvw_kg", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("under_maintenance", "Under Maintenance"),
                            ("retired", "Retired"),
                            ("sold", "Sold"),
                        ],
                        default="active",
                        max_length=50,
                    ),
                ),
                (
                    "current_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
                ("assigned_driver_id", models.UUIDField(blank=True, null=True)),
                ("odometer_km", models.DecimalField(decimal_places=2, max_digits=12)),
                ("avg_daily_km", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "avg_monthly_km",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("trips_per_day", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "fuel_cost_per_month",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "maintenance_cost_per_month",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("insurance_expiry", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "vehicles",
            },
        ),
    ]
