# Generated by Django 6.0.7 on 2026-07-14 01:43

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='bulk_uploads/depots/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_report', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot_bulk_uploads', to='organizations.organization')),
            ],
            options={
                'db_table': 'depot_bulk_uploads',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('parking_capacity', models.IntegerField(default=0)),
                ('workshop_available', models.BooleanField(default=False)),
                ('fuel_station_available', models.BooleanField(default=False)),
                ('charging_available', models.BooleanField(default=False)),
                ('charger_count', models.IntegerField(default=0)),
                ('maintenance_bays', models.IntegerField(default=0)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('depot_manager_name', models.CharField(blank=True, default='', max_length=255)),
                ('depot_manager_contact', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depots', to='organizations.organization')),
            ],
            options={
                'db_table': 'depots',
            },
        ),
    ]
