# Generated by Django 6.0.7 on 2026-07-13 23:45

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('industry', models.CharField(blank=True, default='', max_length=255)),
                ('headquarters_address', models.TextField(blank=True, default='')),
                ('headquarters_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('operating_states', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('operating_cities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('gst_number', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('logo_url', models.URLField(blank=True, default='', max_length=500)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('data_quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
    ]
