# Generated by Django 6.0.8 on 2026-09-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
