# Generated by Django 6.0.7 on 2026-07-14 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_templates', '0001_initial'),
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobtemplate',
            name='destination_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_templates', to='stops.stop'),
        ),
    ]
