# Generated by Django 6.0.8 on 2026-09-09 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('depots', '0001_initial'),
        ('job_templates', '0002_jobtemplate_destination_stop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='destination_stop',
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='destination_depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_job_templates', to='depots.depot'),
        ),
    ]
